spring.application.name=AttendanceService
spring.datasource.url=jdbc:postgresql://localhost:5432/AttendanceManager
spring.datasource.username=postgres
spring.datasource.password=aboba2004
spring.jpa.hibernate.ddl-auto=update
