spring.application.name=EventService
spring.datasource.url=jdbc:postgresql://localhost:5432/EventManager
spring.datasource.username=postgres
spring.datasource.password=aboba2004
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
