spring.application.name=user
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/UserManager
spring.datasource.username=postgres
spring.datasource.password=aboba2004
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driver-class-name=org.postgresql.Driver
